### PR TITLE
added @XmlRootElement annotations to CTOsfTaskpanes.java and CTOsfWeb…

### PR DESCRIPTION
**Pull request by hakarlss**
…Extension.java

More info here: https://www.docx4java.org/forums/docx-java-f6/error-when-trying-to-save-document-as-flat-xml-t2553.html

### CODE REVIEW

**Comment by hugobaes** [comment]
Hi. I'm working on a plugin for Word using docx4j. 
Recently we updated to the latest version, 3.3.5, but we got some errors that I think that is related to this issue:

```
Caused by: com.sun.istack.internal.SAXException2: unable to marshal type "org.docx4j.com.microsoft.schemas.office.webextensions.taskpanes_2010_11.CTOsfTaskpanes" as an element because it is missing an @XmlRootElement annotation
```

I'd like to know if there is a probable date of when it will be fixed?

Thanks!

**Comment by renato-rjps** [comment]
I've had the same problem with the versions (3.3.2, 3.3.3, 3.3.4, 3.3.5 and 3.3.6-SNAPSHOT). 
With the version 3.3.1 it works well.

Hope it will be fixed  soon =)

**Comment by plutext** [comment]
fixed by https://github.com/plutext/docx4j/commit/b0a84a42d3e3673c9713af0f3acfdd408071d950?w=1

expect a nightly later today

**Comment by plutext** [comment]
See now https://www.docx4java.org/docx4j/docx4j-nightly-20170803.jar

**Comment by hugobaes** [comment]
Thank you, very much! That worked! =)

**Pull request closed without merging**
