### PR TITLE
make it possible to turn off automatic deletion of temporary font files

### PR DESCRIPTION
**Pull request by sveale**
- Makes it possible to solve https://github.com/plutext/docx4j/issues/441 without using custom code.

### CODE REVIEW

**Comment by Gitnabb** [comment]
This would certainly fix a lot of issues for me. Please consider this improvement.

**Comment by plutext** [comment]
Thank you for this; merged into 11.5.0.

**Comment by plutext** [comment]
Note deletion can occur from https://github.com/plutext/docx4j/blob/VERSION_11_5_0/docx4j-core/src/main/java/org/docx4j/convert/out/common/AbstractExporter.java#L92 (ie not just in the finalise method

**Comment by sveale** [comment]
Great, thank you! I saw the other call to delete but I think I reasoned that this is not an issue in my case - I'll find out soon enough :)

**Comment by plutext** [comment]
Out of interest, could you please explain the issue which this change helps with?

**Pull request closed without merging**
